### ISSUE TITLE
quant.sh

### ISSUE THREAD

**Issue by yjsdut** [wutianze/dnndk-pynqz2#3]
Hello, According to your instructions, I have successfully performed mnist....I'm running my own yolov3, but I have a problem quantifying pb files:`ValueError: Input 0 of node pred_sbbox/strided_slice_8/aquant was passed int32 from pred_sbbox/strided_slice_8:0 incompatible with expected float.`It hasn't been solved for a long time. Could you please help me.Thank you very much!

**Comment by wutianze** [comment]
It seems like the input of one node needs a float but your input is int. You should check your input value and see what happens. 
Also, I recommend that you check your tensorflow version, if you follow my yolov3 guide(not finished) which has been tested and is not about to come up with this problem.

**Comment by yjsdut** [comment]
Thank you for your reply. I have another question, that is your yolov3 trained in your own environment, **or** is it running under the installation package provided by Xilinx DNNDK and corresponding cuda and cudnn?My yolov3 was a tensorflow1.12.0 version installed in my own environment, I can freeze the graph successfully , but when I run the quant.py in the dnndk environment ,I  have the   problem ,`ValueError: Input 0 of node pred_sbbox/strided_slice_8/aquant was passed int32 from pred_sbbox/strided_slice_8:0 incompatible with expected float.` I think I can use your code if your code finished.

**Comment by wutianze** [comment]
How yolo is trained doesn't matter, all you need is a trained weight file(if you use official darknet). And in my code, I will use some tools to transfer darknet network together with the weight file to a keras model .h5 and then transfer it to a tensorflow model .pb. It seems ugly I know, since when I transfer it directly to .pb it fails. 
If your yolo network is written by yourself, the tensorflow apis you use may be incompatible. Also if you use other tools to do the transformation, it may be incompatible too.
However, from the error info, you can check the graph_input_fn first to see if you feed the model correctly.
